# Generated by Django 5.2.12 on 2026-03-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_date', models.DateField()),
                ('food_name', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField()),
                ('quantity', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-food_date', '-created_at'],
            },
        ),
    ]
